### ISSUE TITLE
Add a management tool for dependencies

### ISSUE THREAD

**Issue by kentork** [kentork/slack-utils#1]
i'm considering to use [this](https://github.com/kennethreitz/pipenv)

**Comment by 82p** [comment]
what's this?
is this can create development environment like vagrant or docker?
anyway I agree if you add readme how to use it.

**Comment by kentork** [comment]
Not exactly.

Vagrant and Docker create a independent **OS** space.
pipenv (actually virtualenv is doing in inside) create a independent **execution environment** for python.
Generally, it is used to make dependency package and python version independent.

> anyway I agree if you add readme how to use it.

Sure. I will add it together when merging changes.
